Controllers/RookiesController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Ass_6.Models;
using System.Globalization;
// using CsvHelper;
// using CsvHelper.TypeConversion;

namespace Ass_6.Controllers;

// [Route("")]
// [Route("NashTech")]
public class RookiesController : Controller
{
    static List<Person> persons = new List<Person>
        {
            new Person
            {
                Id = 1,
                FirstName = "Phuong",
                LastName = "Nguyen Nam",
                Gender = "Male",
                DateOfBirth = new DateTime(2001, 1, 22),
                PhoneNumber = "",
                BirthPlace = "Phu Tho",
                IsGraduated = false
            },
            new Person
            {
                Id = 2,
                FirstName = "Nam",
                LastName = "Nguyen Thanh",
                Gender = "Male",
                DateOfBirth = new DateTime(2001, 1, 20),
                PhoneNumber = "",
                BirthPlace = "Ha Noi",
                IsGraduated = false
            },
            new Person
            {
                Id = 3,
                FirstName = "Son",
                LastName = "Do Hong",
                Gender = "Male",
                DateOfBirth = new DateTime(2000, 11, 6),
                PhoneNumber = "",
                BirthPlace = "Ha Noi",
                IsGraduated = false
            },
            new Person
            {
                Id = 4,
                FirstName = "Huy",
                LastName = "Nguyen Duc",
                Gender = "Male",
                DateOfBirth = new DateTime(1996, 1, 26),
                PhoneNumber = "",
                BirthPlace = "Ha Noi",
                IsGraduated = false
            },
            new Person
            {
                Id = 5,
                FirstName = "Hoang",
                LastName = "Phuong Viet",
                Gender = "Male",
                DateOfBirth = new DateTime(1999, 2, 5),
                PhoneNumber = "",
                BirthPlace = "Ha Noi",
                IsGraduated = false
            },
            new Person
            {
                Id = 6,
                FirstName = "Long",
                LastName = "Lai Quoc",
                Gender = "Male",
                DateOfBirth = new DateTime(1997, 5, 30),
                PhoneNumber = "",
                BirthPlace = "Bac Giang",
                IsGraduated = false
            },
            new Person
            {
                Id = 7,
                FirstName = "Thanh",
                LastName = "Tran Chi",
                Gender = "Male",
                DateOfBirth = new DateTime(2000, 9, 18),
                PhoneNumber = "",
                BirthPlace = "Ha Noi",
                IsGraduated = false
            },
            new Person
            {
                Id = 8,
                FirstName = "Manh",
                LastName = "Le Duc",
                Gender = "Male",
                DateOfBirth = new DateTime(2001,4, 22),
                PhoneNumber = "",
                BirthPlace = "Ha Noi",
                IsGraduated = false
            },
            new Person
            {
                Id = 9,
                FirstName = "Dung",
                LastName = "Dao Tan",
                Gender = "Male",
                DateOfBirth = new DateTime(2000, 12, 7),
                PhoneNumber = "",
                BirthPlace = "Hung Yen",
                IsGraduated = false
            }
        };
    // [Route("rookies")]
    public IActionResult Index(){
        return View(persons);
    }
    
    
    // [Route("rookies/male")]
    public IActionResult GetMaleMembers(){
        var result = from person in persons
                    where person.Gender == "Male"
                    select person;
        // return new ObjectResult(result);
        return Json(result);
    }

    // [Route("rookies/oldest")]
    public IActionResult GetOldestMember(){
        var maxAge = persons.Max(m => m.Age);
        var oldest = persons.First(m =>m.Age == maxAge);
        return new ObjectResult(oldest);
    }

    // [Route("rookies/full-names")]
    public IActionResult GetFullNames(){
        var fullnames = persons.Select(m => m.FullName);
        return new ObjectResult(fullnames);
    }

    // [Route("rookies/split-members-by-year")]
    public IActionResult SplitMemberByYear(int year){
        var results = from person in persons
                    group person by person.DateOfBirth.Year.CompareTo(year) into grp
                    select new 
                    {
                        Key = grp.Key switch
                        {
                            -1 => $"Birth year less than {year}",
                            0 => $"Birth year equals to {year}",
                            1 => $"Birth year greater than {year}",
                            _ => string.Empty
                        },
                        Data = grp.ToList()
                    };
        return Json(results);
    }

    // [Route("rookies/export")]
    // public IActionResult Export()
    // {
    //     var buffer = WriteCsvToMemory(persons); 
    //     var memoryStream = new MemoryStream(buffer);
    //     return new FileStreamResult(memoryStream, "text/csv") { FileDownloadName = "member.csv" };
    // }
    //  public byte[] WriteCsvToMemory(List<Person> data)
    // {
    //     using (var stream = new MemoryStream())
    //     using (var writer = new StreamWriter(stream))
    //     using (var csvWriter = new CsvWriter(writer , CultureInfo.InvariantCulture))
    //     {
    //         var options = new TypeConverterOptions { Formats = new[] { "dd/MM/yyyy" } };
    //         csvWriter.Context.TypeConverterOptionsCache.AddOptions<DateTime>(options);

    //         csvWriter.WriteRecords(data);
    //         writer.Flush();
    //         return stream.ToArray();
    //     }
    // }

    public IActionResult Create(){
        return View();
    }
    [HttpPost]
    public IActionResult Create(Person model){
        if(!ModelState.IsValid) return View();

        persons.Add(model);
        return RedirectToAction("Index");
        
    }
    // [Route("rookies/edit")]
    public IActionResult Edit(int index){
        if (index <= 0 && index > persons.Count){
            return RedirectToAction("Index");
        }
        var person = persons[index -1];

        // var model = new PersonEditModel(person);
        // model.Index = index;
        // return View(model);

        ViewBag.PersonIndex = index;
        return View(person);
    }
    [HttpPost]
    public IActionResult Edit(int index,Person model){
        if(!ModelState.IsValid){
            ViewBag.PersonIndex = index;
            return View();
        }

        persons[index -1] = model;
        return RedirectToAction("Index");
        
    }
    
    public IActionResult Delete(int index){
        if (index <= 0 && index > persons.Count){
            return RedirectToAction("Index");
        }
        
        persons.RemoveAt(index-1);
        return RedirectToAction("Index");
        
    }

}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Ass_6</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Ass_6.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Ass_6</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Rookies" asp-action="Index">Members</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Ass_6 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>